### PR TITLE
feat: Add tracking support for Dragonflight treasures

### PR DESCRIPTION
**Pull request by dillan-prince**

### CODE REVIEW

**Comment by dillan-prince** [comment]
@Nevcairiel

**Comment by ynazar1** [comment]
There's actually a ton more chests that are farmable out there. 
https://www.wowhead.com/objects/shared-containers?filter=17;10;0  basically all the chests and caches on this page. 

I'm really annoyed with GM2 not tracking these too :(

**Comment by ynazar1** [comment]
My (really BAD hack). @dillan-prince if you want to incorporate:
Constants.lua
`
		[NL["Expedition Scout's Pack"]]			= 566,
		[NL["Disturbed Dirt"]]					= 567,
		[NL["Magic-Bound Chest"]]				= 568,
		[NL["Clan Chest"]]						= 569,
		[NL["Decay Covered Chest"]]				= 570,
		[NL["Djaradin Cache"]]					= 571,
		[NL["Dracthyr Supply Chest"]]			= 572,
		[NL["Frostbound Chest"]]				= 573,
		[NL["Ice Bound Chest"]]					= 574,
		[NL["Icemaw Storage Cache"]]			= 575,
		[NL["Lightning Bound Chest"]]			= 576,
		[NL["Molten Chest"]]					= 577,
		[NL["Nomad Cache"]]						= 578,
		[NL["Reed Chest"]]						= 579,
		[NL["Simmering Chest"]]					= 580,
		[NL["Titan Chest"]]						= 581,
		[NL["Tuskarr Chest"]]					= 582,

--
		[566] = icon_path.."Treasure\\treasure.tga",
		[567] = icon_path.."Treasure\\treasure.tga",
		[568] = icon_path.."Treasure\\treasure.tga",
		[569] = icon_path.."Treasure\\treasure.tga",
		[570] = icon_path.."Treasure\\treasure.tga",
		[571] = icon_path.."Treasure\\treasure.tga",
		[572] = icon_path.."Treasure\\treasure.tga",
		[573] = icon_path.."Treasure\\treasure.tga",
		[574] = icon_path.."Treasure\\treasure.tga",
		[575] = icon_path.."Treasure\\treasure.tga",
		[576] = icon_path.."Treasure\\treasure.tga",
		[577] = icon_path.."Treasure\\treasure.tga",
		[578] = icon_path.."Treasure\\treasure.tga",
		[579] = icon_path.."Treasure\\treasure.tga",
		[580] = icon_path.."Treasure\\treasure.tga",
		[581] = icon_path.."Treasure\\treasure.tga",
		[582] = icon_path.."Treasure\\treasure.tga",
`
GatherMate2-enUS.lua
`
NL["Expedition Scout's Pack"] = true
NL["Disturbed Dirt"] = true
NL["Magic-Bound Chest"] = true
NL["Clan Chest"] = true
NL["Decay Covered Chest"] = true
NL["Djaradin Cache"] = true
NL["Dracthyr Supply Chest"] = true
NL["Frostbound Chest"] = true
NL["Ice Bound Chest"] = true
NL["Icemaw Storage Cache"] = true
NL["Lightning Bound Chest"] = true
NL["Molten Chest"] = true
NL["Nomad Cache"] = true
NL["Reed Chest"] = true
NL["Simmering Chest"] = true
NL["Titan Chest"] = true
NL["Tuskarr Chest"] = true
`

**Comment by Nevcairiel** [comment]
I do not plan on adding more treasures like these. There is tons of addons that come with built-in databases of all treasures, as well as tracking of their Quest IDs to hide them when you collected them and all that, which is by far more useful then GM just registering where you saw a treasure before.

**Comment by ynazar1** [comment]
With all due respect, these do respawn and aren't one-time-treasures. I do agree there are plenty of addons for special treasures out there.
Just like Zereth Mortis 'regular' treasures (which are also not tracked :( ), these randomly spawn in their zones and provide small amount of materials and reputation tokens that are relevant to rep grinds for new factions in Dragonflight.

**Comment by ynazar1** [comment]
Meanwhile I'm going to create a version to *only* track those treasures. https://github.com/ynazar1/Gathermate2Treasures  and help me with rep grind.

**Pull request closed without merging**
