### PR TITLE
Optimize tooltip and pin menu display + micro optimizations

### PR DESCRIPTION
**Pull request by Sirbucket**
I noticed a large delay when opening the minimap and also when mousing over, so Im optimizing the parts that were a noticable hotspot in the loading process. This should make it so pins no longer loop through all pins to determine what the text contents of the tooltip will be. Also lightly optimized the loading of pins but its not significant. This also impacts the submenu when you right click.

Sadly not much can be done about the initialization stage as of yet as I don't understand how this codebase fully interacts yet. Give me some time and I can probably make it run fit as a fiddle.

### CODE REVIEW

**Comment by Sirbucket** [comment]
I will also update the classic branch with these optimizations once confirmed and added.

**Comment by Sirbucket** [comment]
There is a noticable improvement in the delay between your mouse hovering a node and the tooltip displaying + submenu loading

**Comment by Sirbucket** [comment]
If you really want to feel the improvement go into the waking shore and hover over a large amount of pins in a clump and the difference is kind of funny.

**Review by Sirbucket — COMMENTED** [review]
- Avoiding iterating over every node after the first hovered node.
>If you mouse hover multiple nodes then this code is reran so each one you hover over will reiterate every single node.

- Reuse newly cached table for right click submenu.
>No brainer and free perf.

- Cache map before loop in map update.
>Not huge but better than nothing, low hanging fruit.

**Comment by Sirbucket** [comment]
- Updated TOC to remove annoying popup message with this addon installed since it has no lua errors.

**Comment by Sirbucket** [comment]
From some testing the lag seems to be caused by engine level texture drawing, maybe I could come up with a solution to reduce this without impacting the addon but It would likely require testing.

**Comment by Sirbucket** [comment]
Maybe a "nodes in a certain radius of each other clump together on the world map" setting would be nice both for visibility and perf. Can look into it if you approve.

**Comment by Nevcairiel** [comment]
The "setting" already exists in a certain manner - run database cleanup that will combine overlapping nodes in a desired radius.

**Comment by Sirbucket** [comment]
I wont lie its been years since I used that setting so I forgot about it, ty for that, do you find these modifications ok?

**Comment by Nevcairiel** [comment]
The world map is largely useless in any modern wow, at least for herbs, since every inch of it is full of nodes. Runtime clustering doesn't really resolve that.

**Comment by Sirbucket** [comment]
That is quite fair, same can be said about mining nodes but I think a view setting like this would still be nice so your eyeballs aren't blown out by the amount of nodes on the map whenever you pop up world map and makes it so you can more accurately gauge what quantity of nodes there are. Maybe the icon could scale in size based on the amount of nodes in said cluster as a visual indicator of more nodes.

**Comment by Sirbucket** [comment]
But thats mostly just me rambling, this branch should be perfectly good to go as far as I am aware.

**Comment by Sirbucket** [comment]
Is there any issue with a merge?

**Comment by Nevcairiel** [comment]
I've manually merged these changes without the block I commented on above. Thank you for the contribution.

**Pull request closed without merging**
